version: '3'
services:
  order-service:
    build: ./
    environment:
#     You are able to specify these because the opentelemetry-javaagent.jar is on your local machine.
      OTEL_TRACES_EXPORTER: "logging"
      OTEL_METRICS_EXPORTER: "logging"
      OTEL_LOGS_EXPORTER: "logging"
    ports:
      - "8080:8080"
